## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [6]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [12]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [14]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [27]:
df['city_encoded'] = df['city'].map(mean_price)

In [29]:
df[['city','city_encoded']]

       city  city_encoded
0  New York         190.0
1    London         150.0
2     Paris         310.0
3     Tokyo         250.0
4  New York         190.0
5     Paris         310.0

## Example

In [2]:
import seaborn as sns

In [6]:
df = sns.load_dataset('tips')

In [8]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

C:\Users\SMART STEP\AppData\Local\Temp\ipykernel_608\927007832.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [30]:
mean_price

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [32]:
df['time_encoded'] = df['time'].map(mean_price)

In [42]:
df[['time','time_encoded']].tail(20)

       time time_encoded
224   Lunch    17.168676
225   Lunch    17.168676
226   Lunch    17.168676
227  Dinner    20.797159
228  Dinner    20.797159
229  Dinner    20.797159
230  Dinner    20.797159
231  Dinner    20.797159
232  Dinner    20.797159
233  Dinner    20.797159
234  Dinner    20.797159
235  Dinner    20.797159
236  Dinner    20.797159
237  Dinner    20.797159
238  Dinner    20.797159
239  Dinner    20.797159
240  Dinner    20.797159
241  Dinner    20.797159
242  Dinner    20.797159
243  Dinner    20.797159