# Used Car Price Prediction

## 1) Problem statement.

* This dataset comprises used cars sold on cardehko.com in India as well as important features of these cars.
* If user can predict the price of the car based on input features.
* Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.
* The Dataset is collected from scrapping from cardheko webiste
* The data consists of 13 column and 15411 rows.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

In [4]:
df= pd.read_csv('cardekho_imputated.csv',index_col=[0])

In [5]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Cleaning
### Handling Missing values

* Handling Missing values 
* Handling Duplicates
* Check data type
* Understand the dataset

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  object
 1   brand              15411 non-null  object
 2   model              15411 non-null  object
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  object
 6   fuel_type          15411 non-null  object
 7   transmission_type  15411 non-null  object
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(6)
memory usage: 1.6+ MB

In [9]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [10]:
df.drop(['car_name','brand'],axis=1,inplace=True)

In [11]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [12]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [13]:
## Getting All Different Types OF Features
num_features = [features for features in df.columns if df[features].dtype !='O']
print('No of Numerical Features: ', len(num_features))
cat_features = [features for features in df.columns if df[features].dtype =='O']
print('No of Categorical Features: ', len(cat_features))
dis_features = [features for features in num_features if len(df[features].unique()) <=25]
print('Num of Discrete Features :',len(dis_features))
cont_features = [features for features in num_features if features not in dis_features]
print('Num of Continous Features :',len(cont_features))

No of Numerical Features:  7
No of Categorical Features:  4
Num of Discrete Features : 2
Num of Continous Features : 5

In [14]:
## Indpendent and dependent features
from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'], axis=1)
y = df['selling_price']

In [15]:
X

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [16]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15411, dtype: int64

## Feature Encoding and Scaling
**One Hot Encoding for Columns which had lesser unique values and not ordinal**
* One hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [18]:
X['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder 
Le = LabelEncoder()
X['model']=Le.fit_transform(X['model'])

In [20]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [21]:
X['seller_type'].unique(),X['fuel_type'].unique(),X['transmission_type'].unique()

(array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object),
 array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object),
 array(['Manual', 'Automatic'], dtype=object))

In [22]:
num_features = X.select_dtypes(exclude='object').columns
onehot_col = ['seller_type','fuel_type','transmission_type']


from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer


preprocessor = ColumnTransformer([

                ('StandardScaler',StandardScaler(),num_features),
                ('OneHotEncoder',OneHotEncoder(),onehot_col)
    
],remainder='passthrough'
                                )

In [23]:
X= preprocessor.fit_transform(X)

In [24]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
4,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
15407,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
15408,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
15409,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
15410,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [25]:
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((12328, 17), (3083, 17))

## Model Training And Model Selection

In [53]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [55]:
def performance_metrics(true,predicted):
    r_score = r2_score(true,predicted)
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mse)
    return r_score,mae,mse,rmse

In [57]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "GradientBoostingRegressor": GradientBoostingRegressor(),
    "XGBoost":XGBRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "Adaboost Regressor":AdaBoostRegressor()
   
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    #make predictions
    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    #evaluation
    r_score_train,mae_train,mse_train,rmse_train = performance_metrics(y_train,y_pred_train)
    r_score_test,mae_test,mse_test,rmse_test = performance_metrics(y_test,y_pred_test)

    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(rmse_train))
    print("- Mean Absolute Error: {:.4f}".format(mae_train))
    print("- R2 Score: {:.4f}".format(r_score_train))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(rmse_test))
    print("- Mean Absolute Error: {:.4f}".format(mae_test))
    print("- R2 Score: {:.4f}".format(r_score_test))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 553855.6665
- Mean Absolute Error: 268101.6071
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502543.5930
- Mean Absolute Error: 279618.5794
- R2 Score: 0.6645
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 553855.6708
- Mean Absolute Error: 268099.3613
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502542.6393
- Mean Absolute Error: 279614.9089
- R2 Score: 0.6645
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 553856.3122
- Mean Absolute Error: 268060.0183
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502533.3688
- Mean Absolute Error: 279558.1057
- R2 Score: 0.6645
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 327338.8125
- Mean Absolute Error: 92306.9922
- R2 Score: 0.8679
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 255092.2781
- Mean Absolute Error: 113608.2793
- R2 Score: 0.9136
===================================


GradientBoostingRegressor
Model performance for Training set
- Root Mean Squared Error: 204046.8519
- Mean Absolute Error: 111666.1918
- R2 Score: 0.9487
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 254273.2763
- Mean Absolute Error: 126049.3510
- R2 Score: 0.9141
===================================


XGBoost
Model performance for Training set
- Root Mean Squared Error: 87247.4721
- Mean Absolute Error: 61798.6066
- R2 Score: 0.9906
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 242741.9332
- Mean Absolute Error: 97315.7961
- R2 Score: 0.9217
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 20797.2352
- Mean Absolute Error: 5164.8199
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 298480.9158
- Mean Absolute Error: 123880.0600
- R2 Score: 0.8817
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 137096.7400
- Mean Absolute Error: 40215.3820
- R2 Score: 0.9768
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 229186.3025
- Mean Absolute Error: 101665.2090
- R2 Score: 0.9302
===================================


Adaboost Regressor
Model performance for Training set
- Root Mean Squared Error: 474037.8523
- Mean Absolute Error: 352515.3109
- R2 Score: 0.7229
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 543050.3952
- Mean Absolute Error: 374601.2668
- R2 Score: 0.6082
===================================

### Hyperparameter Tunning

In [60]:
#Initialize few parameter for Hyperparamter tuning
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]}
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

xgboost_params = { 
                    
                    'learning_rate':[0.1,0.3,0.5,0.7,0.8],
                    "n_estimators":[40,50,60,70,80,100,120],  
                    'max_leaves':[0,1,3,5,8],
                    'max_depth':[1,2,3,4 ]  
}

In [64]:
random_cv_models = [
            ('knn',KNeighborsRegressor(),knn_params),
            ('RF',RandomForestRegressor(),rf_params),
            ('XG Boost',XGBRegressor(),xgboost_params)
]

In [66]:
##Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

model_parm = {}
for name,model,param in random_cv_models:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=param,
                                n_iter=100,
                                cv=3,
                                verbose=3,
                                n_jobs=-1)
    random.fit(X_train,y_train)
    model_parm[name]=random.best_params_      

for model_name in model_parm:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_parm[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------- Best Params for knn -------------------
{'n_neighbors': 10}
---------------- Best Params for RF -------------------
{'n_estimators': 100, 'min_samples_split': 2, 'max_features': 5, 'max_depth': 15}
---------------- Best Params for XG Boost -------------------
{'n_estimators': 50, 'max_leaves': 0, 'max_depth': 4, 'learning_rate': 0.5}

In [68]:
models = {
    "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=10, n_jobs=-1),
    "Random Forest Regressor": RandomForestRegressor(n_estimators=1000, min_samples_split= 2, max_features= 8, max_depth= None),
    "XG Regressor": XGBRegressor(n_estimators= 50, max_leaves= 0, max_depth= 4, learning_rate= 0.5)
   
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    #make predictions
    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    #evaluation
    r_score_train,mae_train,mse_train,rmse_train = performance_metrics(y_train,y_pred_train)
    r_score_test,mae_test,mse_test,rmse_test = performance_metrics(y_test,y_pred_test)

    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(rmse_train))
    print("- Mean Absolute Error: {:.4f}".format(mae_train))
    print("- R2 Score: {:.4f}".format(r_score_train))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(rmse_test))
    print("- Mean Absolute Error: {:.4f}".format(mae_test))
    print("- R2 Score: {:.4f}".format(r_score_test))
    
    print('='*35)
    print('\n')

K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 365913.8572
- Mean Absolute Error: 104821.7716
- R2 Score: 0.8349
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 267328.5397
- Mean Absolute Error: 119002.6679
- R2 Score: 0.9051
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 131551.8084
- Mean Absolute Error: 39117.1173
- R2 Score: 0.9787
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 212675.0119
- Mean Absolute Error: 98737.9590
- R2 Score: 0.9399
===================================


XG Regressor
Model performance for Training set
- Root Mean Squared Error: 140622.5030
- Mean Absolute Error: 88728.7101
- R2 Score: 0.9756
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 329734.6039
- Mean Absolute Error: 113022.1473
- R2 Score: 0.8556
===================================