### Decision Tree Regression

In [4]:
#importing important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Loadind dataset

In [10]:
from sklearn.datasets import load_diabetes

In [12]:
diabetes = load_diabetes()

In [14]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [20]:
X = pd.DataFrame(diabetes['data'],columns=diabetes.feature_names)

In [22]:
X

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [24]:
Y = pd.DataFrame(diabetes['target'])

In [26]:
Y

         0
0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
..     ...
437  178.0
438  104.0
439  132.0
440  220.0
441   57.0

[442 rows x 1 columns]

In [29]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.20,random_state=10)

### Model Implementation

In [122]:
from sklearn.tree import DecisionTreeRegressor

In [124]:
dtr = DecisionTreeRegressor()

In [126]:
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [128]:
y_pred = dtc.predict(X_test)

In [130]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print('Score: ', r2_score(y_pred,y_test))
print('Score: ', mean_squared_error(y_pred,y_test))
print('Score: ', mean_absolute_error(y_pred,y_test))

Score:  -0.2268842364520951
Score:  6893.033707865168
Score:  62.831460674157306

### Hyperparameter Tunning

In [141]:
param_grid = {
        'criterion': ['squared_error','friedman_mse','absolute_error'],
        'splitter':  ['best','random'],
        'max_depth': [1,2,3,4,5,10,15,20,25],
        'max_features': ['auto','sqrt','log2']
}

In [143]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(DecisionTreeRegressor(),param_grid=param_grid,scoring='neg_mean_squared_error')

In [145]:
grid.fit(X_train,y_train)

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
270 fits failed out of a total of 810.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
270 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [           nan            nan -4870.25002043 -5343.582184
 -4860.43622528 -5394.43845744            nan            nan
 -4124.43787002 -4972.85667466 -4080.89354166 -4935.11801156
            nan            nan -4445.43846737 -4970.01541462
 -4767.95380224 -4968.63731917            nan            nan
 -4376.98496407 -4463.17646667 -4546.30907449 -4454.38272069
            nan            nan -4591.97852181 -4572.01507184
 -4260.39577382 -4421.79888397            nan            nan
 -5877.05372663 -4798.30705427 -5871.91011178 -5159.44507476
            nan            nan -6989.29145875 -7198.69211283
 -6797.51250589 -6505.87692419            nan            nan
 -5705.18853119 -6841.38180863 -6892.51275654 -6018.73367315
            nan            nan -6069.51066398 -6905.52096579
 -6173.20684105 -5309.66663984            nan            nan
 -4816.77814916 -4907.5220901  -4697.05516091 -5198.31208993
            nan            nan -4703.00666302 -5156.89839069
 -4016.60920826 -4145.77645315            nan            nan
 -4335.20775053 -4519.86788975 -4167.29695741 -4487.71530453
            nan            nan -4546.60074426 -4720.50187963
 -4010.50232543 -4575.70494952            nan            nan
 -4471.15497559 -4740.92197745 -4922.845559   -4066.8436706
            nan            nan -5707.68958795 -5715.3701207
 -6604.39474406 -5655.06162356            nan            nan
 -6570.75636049 -6377.68155661 -6328.19004918 -6421.31954709
            nan            nan -6365.25650905 -6269.57748491
 -6862.81344064 -5987.4465996             nan            nan
 -6200.85935614 -7088.01871227 -5595.66668008 -6745.73307847
            nan            nan -5262.298833   -5599.12848089
 -5123.44609658 -5416.88181087            nan            nan
 -4800.97855131 -5326.63459759 -4115.37799799 -4995.71152918
            nan            nan -4937.73367203 -4967.85128773
 -4622.90295775 -4887.39885312            nan            nan
 -5243.39721328 -5121.57126761 -4351.01396378 -5022.11302817
            nan            nan -5167.30803823 -4792.75374245
 -5503.13232394 -4455.75350101            nan            nan
 -6721.86696177 -5031.31438632 -5582.10847082 -5053.79811871
            nan            nan -7153.43197183 -6517.20592555
 -6660.41707243 -6604.56348089            nan            nan
 -6094.43326962 -7399.11678068 -6389.08136821 -6883.80284708
            nan            nan -7337.51633803 -7053.27066398
 -6978.08410463 -6974.47472837]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error'],
                         'max_depth': [1, 2, 3, 4, 5, 10, 15, 20, 25],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='neg_mean_squared_error')

In [147]:
grid.best_params_

{'criterion': 'friedman_mse',
 'max_depth': 4,
 'max_features': 'log2',
 'splitter': 'best'}

In [149]:
y_pred = grid.predict(X_test)

In [151]:
print('Score: ', r2_score(y_pred,y_test))
print('Score: ', mean_squared_error(y_pred,y_test))
print('Score: ', mean_absolute_error(y_pred,y_test))

Score:  -0.22257355650404698
Score:  3828.219013832172
Score:  49.31937520782617