### Naive Baye's on Tips Dataset

In [65]:
#importing important libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Loading dataset

In [68]:
df = sns.load_dataset('tips')

In [70]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [74]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [76]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [78]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [80]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [82]:
#dependent and independent features
X = df[['total_bill', 'tip', 'smoker', 'day', 'time']]
Y = df[['sex']]

In [84]:
X

     total_bill   tip smoker   day    time
0         16.99  1.01     No   Sun  Dinner
1         10.34  1.66     No   Sun  Dinner
2         21.01  3.50     No   Sun  Dinner
3         23.68  3.31     No   Sun  Dinner
4         24.59  3.61     No   Sun  Dinner
..          ...   ...    ...   ...     ...
239       29.03  5.92     No   Sat  Dinner
240       27.18  2.00    Yes   Sat  Dinner
241       22.67  2.00    Yes   Sat  Dinner
242       17.82  1.75     No   Sat  Dinner
243       18.78  3.00     No  Thur  Dinner

[244 rows x 5 columns]

In [86]:
Y

        sex
0    Female
1      Male
2      Male
3      Male
4    Female
..      ...
239    Male
240  Female
241    Male
242    Male
243  Female

[244 rows x 1 columns]

### Train Test Split

In [89]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=10)

### Feature Engineering

In [92]:
from sklearn.preprocessing import LabelEncoder

In [94]:
le1 = LabelEncoder()
le2 = LabelEncoder()

In [96]:
X_train['smoker'] = le1.fit_transform(X_train['smoker'])
X_train['time'] = le2.fit_transform(X_train['time'])

In [98]:
X_test['smoker'] = le1.transform(X_test['smoker'] )
X_test['time'] = le2.transform(X_test['time'] )

In [100]:
X_train

     total_bill   tip  smoker   day  time
58        11.24  1.76       1   Sat     0
1         10.34  1.66       0   Sun     0
2         21.01  3.50       0   Sun     0
68        20.23  2.01       0   Sat     0
184       40.55  3.00       1   Sun     0
..          ...   ...     ...   ...   ...
64        17.59  2.64       0   Sat     0
15        21.58  3.92       0   Sun     0
228       13.28  2.72       0   Sat     0
125       29.80  4.20       0  Thur     1
9         14.78  3.23       0   Sun     0

[183 rows x 5 columns]

In [102]:
X_test

     total_bill   tip  smoker   day  time
162       16.21  2.00       0   Sun     0
60        20.29  3.21       1   Sat     0
61        13.81  2.00       1   Sat     0
63        18.29  3.76       1   Sat     0
69        15.01  2.09       1   Sat     0
..          ...   ...     ...   ...   ...
201       12.74  2.01       1  Thur     1
149        7.51  2.00       0  Thur     1
175       32.90  3.11       1   Sun     0
226       10.09  2.00       1   Fri     1
49        18.04  3.00       0   Sun     0

[61 rows x 5 columns]

In [105]:
# OneHotEncoding 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [118]:
ct = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [124]:
import sys
np.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)

In [126]:
X_train

array([[ 1.  ,  0.  ,  0.  , 11.24,  1.76,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.23,  2.01,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 40.55,  3.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 34.81,  5.2 ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 20.53,  4.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 41.19,  5.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 15.06,  3.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 17.82,  1.75,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 26.88,  3.12,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 18.78,  3.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 10.63,  2.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 11.61,  3.39,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 16.43,  2.3 ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 24.27,  2.03,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.36,  1.64,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 32.83,  1.17,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 22.76,  3.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 17.81,  2.34,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 12.48,  2.52,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 17.89,  2.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 26.86,  3.14,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 10.77,  1.47,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.69,  3.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 10.59,  1.61,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 18.15,  3.5 ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 22.67,  2.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 10.65,  1.5 ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 21.5 ,  3.5 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  9.68,  1.32,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 14.31,  4.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 31.85,  3.18,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  2.75,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 29.85,  5.14,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 16.93,  3.07,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 16.4 ,  2.5 ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 10.51,  1.25,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 28.44,  2.56,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 28.55,  2.05,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 19.81,  4.19,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 20.27,  2.83,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 16.  ,  2.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 16.58,  4.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 12.46,  1.5 ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 40.17,  4.73,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 17.26,  2.74,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  ,  3.07,  1.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 16.45,  2.47,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  7.25,  5.15,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.77,  2.23,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 18.69,  2.31,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 29.03,  5.92,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 24.01,  2.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 15.38,  3.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 12.76,  2.23,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 22.12,  2.88,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 13.51,  2.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 19.08,  1.5 ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 22.82,  2.18,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 25.71,  4.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 38.73,  3.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 28.97,  3.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 17.46,  2.54,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 16.66,  3.4 ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 50.81, 10.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 14.  ,  3.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  9.94,  1.56,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 16.29,  3.71,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 23.1 ,  4.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 10.29,  2.6 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 14.83,  3.02,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 19.77,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 10.07,  1.83,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 15.98,  2.03,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 16.27,  2.5 ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 19.65,  3.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 23.68,  3.31,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 39.42,  7.58,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 11.38,  2.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 18.29,  3.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 24.52,  3.48,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 12.03,  1.5 ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 10.34,  2.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 13.94,  3.06,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.45,  3.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 17.29,  2.71,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  7.74,  1.44,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 15.42,  1.57,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 38.07,  4.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 35.26,  5.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 15.69,  1.5 ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 34.83,  5.17,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 18.26,  3.25,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 27.05,  5.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 20.76,  2.24,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 23.17,  6.5 ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.92,  4.08,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 17.78,  3.27,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 18.24,  3.76,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 12.54,  2.5 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 31.71,  4.5 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 48.33,  9.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 34.65,  3.68,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 24.59,  3.61,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 12.26,  2.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 30.4 ,  5.6 ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 27.28,  4.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 10.07,  1.25,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 21.7 ,  4.3 ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  8.51,  1.25,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 16.82,  4.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  8.35,  1.5 ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 30.46,  2.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.53,  3.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 17.07,  3.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 12.43,  1.8 ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 15.48,  2.02,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 27.18,  2.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 14.15,  2.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 14.73,  2.2 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 12.6 ,  1.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 15.98,  3.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 22.75,  3.25,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 13.13,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 14.07,  2.5 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 30.06,  2.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 16.32,  4.3 ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 16.97,  3.5 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 12.69,  2.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 16.31,  2.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 26.41,  1.5 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 18.35,  2.5 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.08,  3.15,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 17.47,  3.5 ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 21.16,  3.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 13.39,  2.61,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  ,  9.55,  1.45,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 13.03,  2.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  ,  5.75,  1.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 34.3 ,  6.7 ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  ,  8.52,  1.48,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 24.55,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 18.43,  3.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 43.11,  5.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 27.2 ,  4.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  ,  8.58,  1.92,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 34.63,  3.55,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 14.48,  2.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 26.59,  3.41,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  1.58,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 18.71,  4.  ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 20.69,  2.45,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 11.02,  1.98,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 14.26,  2.5 ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 25.21,  4.29,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 24.71,  5.85,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 25.56,  4.34,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 13.16,  2.75,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 11.35,  2.5 ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 10.33,  1.67,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 17.31,  3.5 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 17.51,  3.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 16.04,  2.24,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 16.99,  1.01,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 25.28,  5.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 15.04,  1.96,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 35.83,  4.67,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 25.  ,  3.75,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  3.48,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 11.59,  1.5 ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 48.17,  5.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 15.95,  2.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 23.95,  2.55,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 17.59,  2.64,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 21.58,  3.92,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 13.28,  2.72,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 29.8 ,  4.2 ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 14.78,  3.23,  0.  ,  0.  ]])

In [128]:
X_test = ct.transform(X_test)

In [130]:
X_test

array([[ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 18.64,  1.36,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 14.52,  2.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 13.42,  1.68,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 20.9 ,  3.5 ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.81,  3.16,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 10.27,  1.71,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 13.27,  2.5 ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 13.37,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 11.87,  1.63,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 20.69,  5.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 10.33,  2.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  3.08,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 24.08,  2.92,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 11.69,  2.31,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 48.27,  6.73,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 29.93,  5.07,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 28.17,  6.5 ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  8.77,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 12.66,  2.5 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 19.82,  3.18,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 12.9 ,  1.1 ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.65,  3.35,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 12.16,  2.2 ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 20.49,  4.06,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 38.01,  3.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 19.44,  3.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 45.35,  3.5 ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 11.17,  1.5 ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 28.15,  3.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 12.02,  1.97,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 22.49,  3.5 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 13.81,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  9.78,  1.73,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 22.42,  3.48,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  4.08,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 32.4 ,  6.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 16.47,  3.23,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 25.29,  4.71,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  ,  7.25,  1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 21.01,  3.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 12.74,  2.01,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  ,  7.51,  2.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 32.9 ,  3.11,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 10.09,  2.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 18.04,  3.  ,  0.  ,  0.  ]])

### Model Implementation

In [134]:
from sklearn.naive_bayes import GaussianNB

In [136]:
gnb = GaussianNB()

In [138]:
gnb.fit(X_train,y_train)

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [140]:
y_pred = gnb.predict(X_test)

In [143]:
from sklearn.metrics import classification_report

In [145]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      Female       0.55      0.65      0.59        17
        Male       0.85      0.80      0.82        44

    accuracy                           0.75        61
   macro avg       0.70      0.72      0.71        61
weighted avg       0.77      0.75      0.76        61

In [148]:
from sklearn.naive_bayes import BernoulliNB
Bnb = BernoulliNB()
Bnb.fit(X_train,y_train)
y_pred = Bnb.predict(X_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      Female       0.50      0.62      0.56        16
        Male       0.85      0.78      0.81        45

    accuracy                           0.74        61
   macro avg       0.68      0.70      0.68        61
weighted avg       0.76      0.74      0.75        61

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)